### ISSUE TITLE
Asset retrieval by user address to squid-js

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/squid-js#163]
Add asset retrieval by user address as part of squid-js ocean api:

https://github.com/oceanprotocol/commons-marketplace/blob/42720913aec940968bf8d7794defd2a709f138a4/client/src/components/molecules/AssetsUser.tsx#L18

**Comment by Pedro-vk** [comment]
That affects to Squid API, @aaitor I don't know if it's gonna be required necessary on rest of APIs, but form the "marketplace builder" point of view, that's gonna help.

**Comment by aaitor** [comment]
Makes sense, the next specification of Squid could include the methods to retrieve the Consumer/Publisher assets registered.
