### ISSUE TITLE
update web3.js

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/squid-js#220]
I know `beta37` is the best version but by now it creates a bunch of vulnerabilities in our codebases, we try to be in sync with the web3 version used by squid-js.

So check if we can simply upgrade to most recent version, which fixes 4 vulnerabilities marked as `High` in all codebases where we use squid-js.

**Comment by Pedro-vk** [comment]
This PR is gonna be needed on this issue: https://github.com/ethereum/web3.js/pull/2815#pullrequestreview-236614557

**Comment by kremalicious** [comment]
Not needed since the web3.js v1 & v2 split-up. For the time being, we should stay on the kinda stable v1 track which should receive [some fixes in future too](https://github.com/ethereum/web3.js/issues/3070).
