### ISSUE TITLE
Add search capabilities

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/squid-js#26]
* Part of https://github.com/oceanprotocol/ocean/issues/13
* Implemented in `pleuston` in https://github.com/oceanprotocol/pleuston/pull/133

**Comment by H34D** [comment]
closes with #34

**Comment by JohnBDB** [comment]
What's the status about the integration in Pleuston @jernejpregelj ?

**Comment by jernejpregelj** [comment]
@JohnBDB I'm finishing UI part, everything else is working on Pleuston side.
On squid-js side the documentation and squid-js needs to be updated to be in line with https://github.com/oceanprotocol/aquarius/commit/e6fdadaafa1f870409fcf5f1fb0d6aa9ffa47be0

**Comment by JohnBDB** [comment]
Missing the aquarius fix @innoprenuer @eruizgar91 @ssallam (https://github.com/oceanprotocol/pleuston/issues/168)

**Comment by H34D** [comment]
fixed with `v0.1.16`
