### ISSUE TITLE
proposal: rename to squid-js

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/squid-js#3]
<img width="517" alt="screen shot 2018-08-31 at 10 30 32" src="https://user-images.githubusercontent.com/13647606/45085319-acadfc80-b100-11e8-9b08-e8cd51592b3c.png">

**Comment by kremalicious** [comment]
The package name should still be ‘@oceanprotocol/squid’, no?

From the npm docs:
> Don't put "js" or "node" in the name. It's assumed that it's js, since you're writing a package.json file

**Comment by H34D** [comment]
I agree, will change

**Comment by H34D** [comment]
https://github.com/oceanprotocol/pleuston/pull/92
https://github.com/oceanprotocol/squid-js/pull/4
