### ISSUE TITLE
Feature request: allow Aquarius method execution without connecting to the network

### ISSUE THREAD

**Issue by santteegt** [oceanprotocol/squid-js#335]
## Expected Behavior

Be able to import and execute API calls to Aquarius off-chain metadata DB without the need to connect to the network

## Current Behavior

In order to call Aquarius methods, a client always needs to connect to the network

### Possible Solution

Allow to directly import and execute an instance of `Aquarius` so marketplaces can improve the UX experience by allowing e.g. better onboarding experiences and on/off ramp for web2 users, minimize blockchain interactions and thus maximize finality, etc

**Comment by kremalicious** [comment]
agreed, that would be nice.

As a workaround for the time being, you can call the Aquarius API endpoints directly without squid-js, see https://docs.oceanprotocol.com/references/aquarius/

**Comment by ssallam** [comment]
You can also use squid-py without having to connect to web3. Just use the Aquarius class directly.
