### ISSUE TITLE
transferOwnership should update owner in DDO in aquarius

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/squid-js#358]
# Prerequisites

https://aquarius.marketplace.dev-ocean.com/api/v1/aquarius/assets/ddo/did:op:55d3f9b1a4ae4493a9637e6da99c2c5daf98d3bb16224250aa595d57e63a26a5

Old Owner: 0x376817c638d2a04f475a73af37f7b51a2862d567
New Owner:0xC41808BBef371AD5CFc76466dDF9dEe228d2BdAA

Transfer transaction:
{ blockHash:
   '0xa92e521562960c61047f48bdee6b8b1896d70409f091bb185723ad53b36750df',
  blockNumber: 3842369,
  contractAddress: null,
  cumulativeGasUsed: 34734,
  from: '0x376817c638d2a04f475a73af37f7b51a2862d567',
  gasUsed: 34734,
  logsBloom:
   '0x00000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020400020000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000',
  root: null,
  status: true,
  to: '0x4a0f7f763b1a7937aed21d63b2a78adc89c5db23',
  transactionHash:
   '0x533f96f90f81f43e71a0d349a620dfb648965f893ddbbe20978e06b64b134daf',
  transactionIndex: 0,
  events:
   { DIDOwnershipTransferred:
      { address: '0x4A0f7F763B1A7937aED21D63b2A78adc89c5Db23',
        blockHash:
         '0xa92e521562960c61047f48bdee6b8b1896d70409f091bb185723ad53b36750df',
        blockNumber: 3842369,
        logIndex: 0,
        removed: false,
        transactionHash:
         '0x533f96f90f81f43e71a0d349a620dfb648965f893ddbbe20978e06b64b134daf',
        transactionIndex: 0,
        transactionLogIndex: '0x0',
        type: 'mined',
        id: 'log_45011323',
        returnValues: [Result],
        event: 'DIDOwnershipTransferred',
        signature:
         '0xe36e06a31618f1e5c2057e2d659c72bb4d1e19526236dc13052a483978b55ea2',
        raw: [Object] } } }

**Comment by kremalicious** [comment]
this goes into this issue of updating/deleting assets. Aquarius has this implemented as `PUT` on `/assets/ddo/{did}` but the `PUT` method is blocked on nginx level for all our Aquarius installations I think. If we open that up, everyone can update all DDOs.

The solution was to implement authenticated API calls, which seems already in place in squid-js. But Aquarius does not have it, there's still an open PR https://github.com/oceanprotocol/aquarius/pull/210

So I could just extend the `ocean.assets.transferOwnership()` method and create a new `updateDDO()` method for ocean.aquarius. But then it depends on `PUT` method being allowed somehow
