### ISSUE TITLE
React integration failure

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/squid-js#37]
# Prerequisites

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository.

## Expected Behavior

Compiling and running integrated with React.

## Current Behavior

Compilation of React stops with error.

## Step to Reproduce the problem

Running Pleuston with .18 version of Squid-js

## Failure Logs

![screenshot 2018-10-30 at 10 10 46](https://user-images.githubusercontent.com/7147341/47707639-a2097280-dc2c-11e8-8b31-0b982476e2c1.png)

**Comment by H34D** [comment]
its caused by https://github.com/oceanprotocol/secret-store-client-js

it depends on jaysonl, i have opened an issue: https://github.com/oceanprotocol/secret-store-client-js/issues/1

**Comment by H34D** [comment]
opened a PR https://github.com/oceanprotocol/secret-store-client-js/pull/2

**Comment by H34D** [comment]
solved with v0.1.0-beta.19
