### ISSUE TITLE
Loading of contracts fails

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/squid-js#38]
## Expected Behavior

Squid gets fully loaded

## Current Behavior

Loading of contracts fails with error

## Step to Reproduce the problem

Initialize @oceanprotocol/squid@0.1.0-beta.19 instance.

## Failure Logs

![screenshot 2018-10-30 at 15 20 37](https://user-images.githubusercontent.com/7147341/47725022-14437c80-dc58-11e8-97cf-eedddf697d9d.png)

**Comment by H34D** [comment]
ServiceAgreement is not deployed to kovan (yet)

**Comment by jernejpregelj** [comment]
Closing this since we use local node.
