### ISSUE TITLE
Update documentation with compute endpoints

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/squid-js#382]

**Comment by kremalicious** [comment]
the docs for squid-js get their data from the latest release asset `squid-js.json` which gets autogenerated during release script execution. As all the v2 releases are labeled as pre-releases on GitHub, the docs will not grab them.

There is nothing specific to do to update the docs, except for doing an actual release (not pre-release) with the release scripts. Docs gets autogenerated once per day and upon next deployment will have the changes
