### ISSUE TITLE
Search query error

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/squid-js#50]
## Expected Behavior

Retrival of search results from ocean.searchAssets.

## Current Behavior

Retrival of empty array from ocean.searchAssets even if network request had data returned and error message.

## Failure Information (for bugs)

<img width="1279" alt="screenshot 2018-11-15 at 14 07 04" src="https://user-images.githubusercontent.com/7147341/48556221-a6e44c80-e8e3-11e8-9217-eae25d1ca012.png">

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Execute ocean.searchAssets

## Specifications

* Version: 0.1.12

**Comment by H34D** [comment]
fixed with `v0.1.16`
