### ISSUE TITLE
Save asset data is broken.

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/squid-js#76]
## Expected Behavior

Consume asset saves downloaded content to disk in `downloads` folder specified by config setting.

## Current Behavior

* Attempts to save the download in `.../node_modules/@oceanprotocol/squid/dist/node/ocean/downloads`
* File is not saved

## Version
0.2.3

## Steps
1. Start ocean using the docker-images `start_ocean.sh` script
1. Use tuna to register an asset, then trigger the `sea/sign` agreement feature with the new `did`

**Comment by H34D** [comment]
closes with #78
