### ISSUE TITLE
Add documentation in the code to all the public and private methods

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/squid-js#80]
This documentation for each method should include:

* The intention of the method
* Input parameters and data types, data formats (i.e if is a did should include or not the 0x)
* Output
* Exceptions raised in the code

**Comment by H34D** [comment]
duplicate of #68

**Comment by ttmc** [comment]
I'm closing this because it's now a duplicate of #79 (which started out as an issue with a broader scope).
