### ISSUE TITLE
get `conditionKeys` from keeper-contracts rather than DDO.service

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/squid-js#82]
The DDO isn't the source of truth for the `conditionKeys`, but `keeper-contracts.SLA.serviceAgreementTemplate` is.

This leads to interesting behavior when re-computing the `conditionKeys`. For example one could have a faulty DDO, or one created before a contract migration.

see: https://github.com/oceanprotocol/squid-js/blob/develop/src/ocean/ServiceAgreements/ServiceAgreement.ts#L74

This also applies to `squid-py`.

Another way to avoid is to exclude the `conditionKeys` from the hash. Which might lead to problems with mapping `conditionValues`

**Comment by diminator** [comment]
Flagged this as a bug, because for me that was the reason why `isValidSignature` was failing on `keeper-contracts.SLA.ServiceAgreement.executeAgreement`

**Comment by H34D** [comment]
Well, this depends a bit on the requirements. If we want to invalidate a DDO (the condition keys to be precise) once we change the addresses of the contracts we could leave it like it is. If we don't want that we can change it to auto computation of those keys on the fly.

**Comment by H34D** [comment]
> Flagged this as a bug, because for me that was the reason why `isValidSignature` was failing on `keeper-contracts.SLA.ServiceAgreement.executeAgreement`

This happens only if you use different addresses

**Comment by H34D** [comment]
If we do this we should delete condition keys from DDO completly.
