### ISSUE TITLE
Registering asset fails on secret-store

### ISSUE THREAD

**Issue by jernejpregelj** [oceanprotocol/squid-js#84]
## Expected Behavior

Process of registering asset finishes without the secret store error.

## Current Behavior

Process of registering asset is stopped with error from secret store.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Run docker-images
2. Setup Pleuston
3. Register asset

## Failure Logs
```
secret-store_1               | 2018-12-17 09:20:33 UTC Ignoring invalid POST-request /shadow/0xe1975887dfa54986a4c4bb8ccf55cc5e6d11d008e49242cca72ae38fdb2ae2aa/c7d6fb9707affc6290d36fc24f1b31f2a4b4e46c50c2679788fc76215d7cf4c7721a2ea22ec98ba90e96ecb979a546b8471533dff21156be9005b42ffb70dc8601/0
```

**Comment by H34D** [comment]
we should rollback the addition of `0x` to the asset id from #77

**Comment by H34D** [comment]
closing with #86

**Comment by jernejpregelj** [comment]
The error still persists with Metamask using @oceanprotocol/squid:0.2.4

`secret-store_1               | 2019-01-07 10:52:57 UTC Ignoring invalid POST-request /shadow/0xaa342cf59ea541e4b2937fb61ca02b54d6b33d0ffe0949809cc88096c0fb6229/7813728cafc292b01b1ba47c8dd1d10e6173031ffe217cad19de1a869b05e7322f0b0512e9b54de84f1d3b51bbed6b8b3acceda6366d748d5bdaa2fb69f6331f00/0
`

**Comment by jernejpregelj** [comment]
Works with 0.2.5 relase.

**Comment by H34D** [comment]
> Works with 0.2.5 relase.

nice
